const products = [
  { category: 'Крем для рук / уход', name: 'Крем для рук Doctor\'s Secrets', description: 'Крем для рук с увлажняющим и питательным эффектом, в тубе', weight: 'не указано (стандартный тюбик)', price: 'error404' },
  { category: 'Крем для рук / уход', name: 'Крем для рук "Нежные Ручки" питательный', description: 'Питательный крем для рук с натуральными компонентами', weight: 'не указано', price: 'error404' },
  { category: 'Крем для рук / уход', name: 'Крем для рук "Бархатные Ручки" нежное очищение', description: 'Крем для рук с эффектом бархатной кожи', weight: 'не указано', price: 'error404' },
  { category: 'Крем для рук / уход', name: 'Крем для рук "Велюр"', description: 'Крем для рук с эффектом велюровой кожи', weight: 'не указано', price: 'error404' },
  { category: 'Крем для рук / уход', name: 'Крем Боро Плюс антисептический', description: 'Антисептический крем для ухода за кожей, лечебные травы', weight: '25 мл', price: 'error404' },
  { category: 'Крем для рук / уход', name: 'Крем Боро Плюс (скин кэйр)', description: 'Крем для ухода за кожей, антисептическое действие', weight: 'не указано', price: 'error404' },
  { category: 'Крем для рук / уход', name: 'Детский крем "Алиса"', description: 'Детский увлажняющий крем', weight: 'не указано', price: 'error404' },
  { category: 'Крем для рук / уход', name: 'Детский крем "Тик-Так"', description: 'Детский крем для ухода за кожей', weight: 'не указано', price: 'error404' },
  { category: 'Крем для рук / уход', name: 'Огуречный крем для рук', description: 'Крем для рук с экстрактом огурца, увлажняющий', weight: 'не указано', price: 'error404' },
  { category: 'Крем для рук / уход', name: 'Крем для рук Belle Jardin Goat\'s Milk', description: 'Смягчающий крем для рук с козьим молоком', weight: 'не указано', price: 'error404' },
  { category: 'Детская гигиена (Johnson\'s)', name: 'Детское масло Johnson\'s Baby', description: 'Увлажняющее масло для младенцев', weight: 'не указано', price: 'error404' },
  { category: 'Детская гигиена (Johnson\'s)', name: 'Детская присыпка Johnson\'s Baby', description: 'Классическая детская присыпка', weight: '50 г', price: 'error404' },
  { category: 'Детская гигиена (Johnson\'s)', name: 'Детская присыпка Johnson\'s Baby Powder (розовая)', description: 'Детская присыпка', weight: '100 г', price: 'error404' },
  { category: 'Детская гигиена (Johnson\'s)', name: 'Детская присыпка Johnson\'s Baby Powder (фиолетовая)', description: 'Детская присыпка', weight: '200 г', price: 'error404' },
  { category: 'Детская гигиена (Johnson\'s)', name: 'Детская присыпка Johnson\'s Baby (белая)', description: 'Детская присыпка', weight: '100 г', price: 'error404' },
  { category: 'Детская гигиена (Johnson\'s)', name: 'Детский шампунь Johnson\'s "Блестящие локоны"', description: 'Детский шампунь для волос, бережное очищение', weight: '300 мл', price: 'error404' },
  { category: 'Мыло Johnson\'s', name: 'Детский шампунь Johnson\'s "Блестящие локоны" мини', description: 'Детский шампунь для волос', weight: '100 мл', price: 'error404' },
  { category: 'Мыло Johnson\'s', name: 'Мыло Johnson\'s Body Care Vita-Rich (папайя)', description: 'Смягчающее мыло с экстрактом папайи', weight: '125 г', price: 'error404' },
  { category: 'Мыло Johnson\'s', name: 'Мыло Johnson\'s baby детское (перед сном)', description: 'Детское мыло с ароматом для спокойного сна', weight: '100 г', price: 'error404' },
  { category: 'Мыло Johnson\'s', name: 'Мыло Johnson\'s Body Care Vita-Rich (гранат)', description: 'Преображающее мыло с экстрактом граната', weight: '125 г', price: 'error404' },
  { category: 'Мыло Johnson\'s', name: 'Мыло Johnson\'s Body Care Vita-Rich (малина)', description: 'Восстанавливающее мыло с экстрактом малины', weight: '125 г', price: 'error404' },
  { category: 'Освежители воздуха', name: 'Освежитель воздуха Air Time (тропик)', description: 'Аэрозольный освежитель воздуха, аромат тропических фруктов', weight: 'не указано', price: 'error404' },
  { category: 'Освежители воздуха', name: 'Освежитель воздуха Air Time (океан)', description: 'Аэрозольный освежитель воздуха, морской аромат', weight: 'не указано', price: 'error404' },
  { category: 'Освежители воздуха', name: 'Освежитель воздуха Air Time (лимон)', description: 'Аэрозольный освежитель воздуха, цитрусовый аромат', weight: 'не указано', price: 'error404' },
  { category: 'Освежители воздуха', name: 'Освежитель воздуха Air Time (орхидея)', description: 'Аэрозольный освежитель воздуха, аромат орхидеи, мини-формат', weight: 'не указано', price: 'error404' },
  { category: 'Детское мыло', name: 'Детское мыло "Малышам" Весна', description: 'Детское мыло с рождения, гипоаллергенное', weight: 'не указано', price: 'error404' },
  { category: 'Детское мыло', name: 'Детское крем-мыло "Детское" Весна', description: 'Крем-мыло с экстрактом череды, дерматологически одобрено', weight: 'не указано', price: 'error404' },
  { category: 'Парфюмированное мыло', name: 'Мыло Camay (разные ароматы)', description: 'Парфюмированное туалетное мыло, разные ароматы (алоэ, клубника, лаванда, роза и др.)', weight: 'не указано', price: 'error404' },
  { category: 'Парфюмированное мыло', name: 'Мыло Fax Wildberry Bloom', description: 'Туалетное мыло с ароматом лесных ягод, с глицерином', weight: 'не указано', price: 'error404' },
  { category: 'Парфюмированное мыло', name: 'Мыло Dove Beauty Cream Bar (классик)', description: 'Увлажняющее мыло с 1/4 увлажняющего крема', weight: 'не указано', price: 'error404' },
  { category: 'Парфюмированное мыло', name: 'Мыло Dove Purely Pampering (кокосовое молоко)', description: 'Увлажняющее мыло с ароматом кокосового молока', weight: 'не указано', price: 'error404' },
  { category: 'Товары для кормления/ГВ', name: 'Мыло Dove (масло ши / огурец / малина)', description: 'Увлажняющее мыло, различные варианты аромата', weight: 'не указано', price: 'error404' },
  { category: 'Товары для кормления/ГВ', name: 'Накладки на грудь (силиконовые)', description: 'Накладки для кормления, силиконовые, для чувствительной груди', weight: 'не указано', price: 'error404' },
  { category: 'Товары для кормления/ГВ', name: 'Соски для бутылочек (силиконовые)', description: 'Сменные соски для детских бутылочек', weight: 'не указано', price: 'error404' },
  { category: 'Товары для кормления/ГВ', name: 'Носовой аспиратор детский', description: 'Аспиратор для чистки носа младенца', weight: 'не указано', price: 'error404' },
  { category: 'Товары для кормления/ГВ', name: 'Молокоотсос ручной', description: 'Ручной молокоотсос для кормящих мам', weight: 'не указано', price: 'error404' },
  { category: 'Соски / пустышки', name: 'Трусики для обряда обрезания (Сунат кийими)', description: 'Специальные трусики для мальчиков после обряда обрезания', weight: 'не указано', price: 'error404' },
  { category: 'Соски / пустышки', name: 'Прорезыватель для зубов (силиконовый)', description: 'Игрушка-прорезыватель для первых зубов, разные формы', weight: 'не указано', price: 'error404' },
  { category: 'Соски / пустышки', name: 'Пустышка с клипсой-держателем (корона/коала)', description: 'Держатель для пустышки с силиконовыми бусинами и подвеской', weight: 'не указано', price: 'error404' },
  { category: 'Соски / пустышки', name: 'Цепочка-держатель для пустышки', description: 'Клипса-цепочка для крепления пустышки', weight: 'не указано', price: 'error404' },
  { category: 'Детские бутылочки', name: 'Пустышка ортодонтическая (оранжевая/жёлтая)', description: 'Классическая ортодонтическая пустышка', weight: 'не указано', price: 'error404' },
  { category: 'Детские бутылочки', name: 'Пустышки фигурные (декоративные)', description: 'Декоративные пустышки различных форм (губы, усы, зверята)', weight: 'не указано', price: 'error404' },
  { category: 'Детские бутылочки', name: 'Ниблер / поильник-сетка для прикорма', description: 'Ниблер для безопасного прикорма фруктами и овощами', weight: 'не указано', price: 'error404' },
  { category: 'Детские бутылочки', name: 'Детская бутылочка mummy с ручками', description: 'Бутылочка для кормления с удобными ручками', weight: '150 мл', price: 'error404' },
  { category: 'Гигиена / салфетки', name: 'Детская бутылочка mummy (большая)', description: 'Бутылочка для кормления', weight: '250 мл', price: 'error404' },
  { category: 'Гигиена / салфетки', name: 'Детская бутылочка Panda', description: 'Детская бутылочка для кормления', weight: '150 мл', price: 'error404' },
  { category: 'Гигиена / салфетки', name: 'Детская бутылочка Panda (большая)', description: 'Детская бутылочка для кормления', weight: '250 мл', price: 'error404' },
  { category: 'Гигиена / салфетки', name: 'Влажные салфетки детские Sunlight (ромашка)', description: 'Влажные салфетки для детей, без спирта и парабенов', weight: '120 шт', price: 'error404' },
  { category: 'Зубные щётки', name: 'Влажные салфетки детские Rio', description: 'Влажные детские салфетки, без спирта и парабенов', weight: '120 шт', price: 'error404' },
  { category: 'Зубные щётки', name: 'Влажные салфетки детские Sleepy', description: 'Влажные детские салфетки', weight: '120 шт', price: 'error404' },
  { category: 'Чистотело', name: 'Бумажные полотенца (рулон)', description: 'Бумажные полотенца в рулоне, 2 слоя', weight: '4 рулона', price: 'error404' },
  { category: 'Чистотело', name: 'Зубная щётка детская Dentissimo', description: 'Детская зубная щётка, мягкая щетина, для 2-6 лет', weight: '1 шт', price: 'error404' },
  { category: 'Детские присыпки', name: 'Зубная щётка Colgate', description: 'Зубная щётка', weight: '1 шт', price: 'error404' },
  { category: 'Детские присыпки', name: 'Чистотело (от бородавок)', description: 'Средство для наружного применения, избавляет от бородавок и папиллом', weight: '1 мл', price: 'error404' },
  { category: 'Детские присыпки', name: 'Чистотело супер (от бородавок)', description: 'Усиленное средство от бородавок и папиллом', weight: '3 мл', price: 'error404' },
  { category: 'Детские присыпки', name: 'Детская присыпка (базовая)', description: 'Детская присыпка классическая', weight: '20 г', price: 'error404' },
  { category: 'Женская гигиена', name: 'Детская присыпка (средняя)', description: 'Детская присыпка классическая', weight: '30 г', price: 'error404' },
  { category: 'Женская гигиена', name: 'Детская присыпка (большая)', description: 'Детская присыпка классическая', weight: '50 г', price: 'error404' },
  { category: 'Женская гигиена', name: 'Детская присыпка (макси)', description: 'Детская присыпка классическая', weight: '100 г', price: 'error404' },
  { category: 'Женская гигиена', name: 'Прокладки Onajon Super Classic', description: 'Женские гигиенические прокладки', weight: '10 шт', price: 'error404' },
  { category: 'Женская гигиена', name: 'Прокладки Sofi Extra Wings', description: 'Женские гигиенические прокладки с крылышками', weight: '10 шт', price: 'error404' },
  { category: 'Женская гигиена', name: 'Прокладки Atirgul Classic', description: 'Женские гигиенические прокладки', weight: '10 шт', price: 'error404' },
  { category: 'Подгузники', name: 'Тампоны Vita', description: 'Гигиенические тампоны', weight: 'не указано', price: 'error404' },
  { category: 'Подгузники', name: 'Прокладки Discreet Deo (водяная лилия)', description: 'Ежедневные прокладки с дышащим слоем, аромат водяной лилии', weight: '20 шт', price: 'error404' },
  { category: 'Подгузники', name: 'Прокладки Ola! без аромата', description: 'Ежедневные прокладки, гипоаллергенные, без отдушек', weight: '60 шт', price: 'error404' },
  { category: 'Подгузники', name: 'Подгузники для взрослых Evony XL', description: 'Подгузники для взрослых, защита от протекания на всю ночь', weight: '30 шт (XL, 120-170 см)', price: 'error404' },
  { category: 'Детские шампуни', name: 'Подгузники для взрослых Evony L', description: 'Подгузники для взрослых, защита от протекания на всю ночь', weight: '30 шт (L, 100-150 см)', price: 'error404' },
  { category: 'Детские шампуни', name: 'Подгузники Perla Comfort Plus (размер 4)', description: 'Детские подгузники Mega Pack, 7-18 кг', weight: '50 шт', price: 'error404' },
  { category: 'Детские шампуни', name: 'Подгузники Perla Comfort Plus (размер 5)', description: 'Детские подгузники Mega Pack, 11-25 кг', weight: '42 шт', price: 'error404' },
  { category: 'Детские шампуни', name: 'Подгузники Perla Comfort Plus (размер 3)', description: 'Детские подгузники Mega Pack, 7-18 кг', weight: '50 шт', price: 'error404' },
  { category: 'Детские шампуни', name: 'Подгузники Perla Comfort Plus (размер 2)', description: 'Детские подгузники Mega Pack, 3-6 кг', weight: '70 шт', price: 'error404' },
  { category: 'Детские шампуни', name: 'Детский шампунь Baby (Эльза)', description: 'Детский шампунь для волос', weight: 'не указано', price: 'error404' },
  { category: 'Детские шампуни', name: 'Детский шампунь "Детский" (клубника)', description: 'Детский шампунь для волос с клубникой', weight: 'не указано', price: 'error404' },
  { category: 'Детские шампуни', name: 'Детский шампунь "Малыш"', description: 'Детский шампунь для волос', weight: 'не указано', price: 'error404' },
  { category: 'Тесты на беременность', name: 'Детский шампунь "Кря-Кря"', description: 'Детский шампунь для волос', weight: 'не указано', price: 'error404' },
  { category: 'Тесты на беременность', name: 'Детский шампунь Velton Kids', description: 'Детский шампунь для волос, без слёз', weight: 'не указано', price: 'error404' },
  { category: 'Медицинские расходники', name: 'Детский шампунь Velton (разные линейки)', description: 'Детский шампунь для волос, различные варианты', weight: 'не указано', price: 'error404' },
  { category: 'Детские бутылочки', name: 'Детская бутылочка с ручками (Fine)', description: 'Бутылочка для кормления с ручками, для самостоятельного питья', weight: '280 мл', price: 'error404' },
  { category: 'Детские бутылочки', name: 'Детская бутылочка Baby Land', description: 'Детская бутылочка для кормления, декоративная крышка-игрушка', weight: 'не указано', price: 'error404' },
  { category: 'Тесты на беременность', name: 'Тест на беременность Aibo test', description: 'Тест для определения беременности, с первого дня задержки, результат за 5 минут', weight: '1 тест', price: 'error404' },
  { category: 'Тесты на беременность', name: 'Тест на беременность "Определенность"', description: 'Тест на беременность одним движением', weight: '1 тест', price: 'error404' },
  { category: 'Медицинские расходники', name: 'Скальпель одноразовый стерильный', description: 'Стерильный одноразовый скальпель, гамма-стерилизация', weight: '1 шт', price: 'error404' },
  { category: 'Зубные щётки', name: 'Детская зубная щётка "Панда"', description: 'Детская зубная щётка с фигуркой панды', weight: '1 шт', price: 'error404' },
];

module.exports = products;
